/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletedWorkout {
  'completedAt' : Timestamp,
  'completedId' : bigint,
  'planId' : bigint,
  'userId' : UserId,
  'dayOfWeek' : string,
  'exercises' : Array<Exercise>,
  'difficultyFeedback' : DifficultyFeedback,
}
export interface DayPlan {
  'dayOfWeek' : string,
  'exercises' : Array<Exercise>,
  'isRestDay' : boolean,
}
export type DifficultyFeedback = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Exercise {
  'intensityDescriptor' : string,
  'restSeconds' : bigint,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'muscleGroup' : string,
}
export type ExperienceLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type FitnessGoal = { 'weightLoss' : null } |
  { 'flexibility' : null } |
  { 'muscleGain' : null } |
  { 'maintenance' : null } |
  { 'endurance' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface GoalPrediction {
  'weeklyRateKg' : number,
  'estimatedWeeksRemaining' : [] | [number],
  'currentWeightKg' : number,
  'progressPercent' : number,
  'targetWeightKg' : [] | [number],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfileInput {
  'age' : bigint,
  'experienceLevel' : ExperienceLevel,
  'fitnessGoal' : FitnessGoal,
  'heightCm' : number,
  'name' : string,
  'weightKg' : number,
  'targetWeightKg' : [] | [number],
  'gender' : Gender,
}
export interface UserProfilePublic {
  'age' : bigint,
  'experienceLevel' : ExperienceLevel,
  'fitnessGoal' : FitnessGoal,
  'heightCm' : number,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'weightKg' : number,
  'targetWeightKg' : [] | [number],
  'gender' : Gender,
  'intensityModifier' : bigint,
}
export interface UserStats {
  'averageDifficultyScore' : number,
  'totalWorkoutsCompleted' : bigint,
  'currentStreak' : bigint,
}
export interface WeeklyWorkoutPlan {
  'planId' : bigint,
  'userId' : UserId,
  'days' : Array<DayPlan>,
  'generatedAt' : Timestamp,
  'intensityModifierAtGeneration' : bigint,
  'weekNumber' : bigint,
}
export interface WeightEntry {
  'userId' : UserId,
  'entryId' : bigint,
  'weightKg' : number,
  'loggedAt' : Timestamp,
}
export interface _SERVICE {
  'generateWorkoutPlan' : ActorMethod<[], WeeklyWorkoutPlan>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCompletedWorkouts' : ActorMethod<[], Array<CompletedWorkout>>,
  'getGoalPrediction' : ActorMethod<[], GoalPrediction>,
  'getLatestWorkoutPlan' : ActorMethod<[], [] | [WeeklyWorkoutPlan]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'getWeightHistory' : ActorMethod<[], Array<WeightEntry>>,
  'getWorkoutStats' : ActorMethod<[], UserStats>,
  'logWeight' : ActorMethod<[number], WeightEntry>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], UserProfilePublic>,
  'submitWorkoutFeedback' : ActorMethod<
    [bigint, string, Array<Exercise>, DifficultyFeedback],
    CompletedWorkout
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];