/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Exercise = IDL.Record({
  'intensityDescriptor' : IDL.Text,
  'restSeconds' : IDL.Nat,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'muscleGroup' : IDL.Text,
});
export const DayPlan = IDL.Record({
  'dayOfWeek' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'isRestDay' : IDL.Bool,
});
export const Timestamp = IDL.Int;
export const WeeklyWorkoutPlan = IDL.Record({
  'planId' : IDL.Nat,
  'userId' : UserId,
  'days' : IDL.Vec(DayPlan),
  'generatedAt' : Timestamp,
  'intensityModifierAtGeneration' : IDL.Int,
  'weekNumber' : IDL.Nat,
});
export const ExperienceLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const FitnessGoal = IDL.Variant({
  'weightLoss' : IDL.Null,
  'flexibility' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintenance' : IDL.Null,
  'endurance' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'age' : IDL.Nat,
  'experienceLevel' : ExperienceLevel,
  'fitnessGoal' : FitnessGoal,
  'heightCm' : IDL.Float64,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'weightKg' : IDL.Float64,
  'targetWeightKg' : IDL.Opt(IDL.Float64),
  'gender' : Gender,
  'intensityModifier' : IDL.Int,
});
export const DifficultyFeedback = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const CompletedWorkout = IDL.Record({
  'completedAt' : Timestamp,
  'completedId' : IDL.Nat,
  'planId' : IDL.Nat,
  'userId' : UserId,
  'dayOfWeek' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'difficultyFeedback' : DifficultyFeedback,
});
export const GoalPrediction = IDL.Record({
  'weeklyRateKg' : IDL.Float64,
  'estimatedWeeksRemaining' : IDL.Opt(IDL.Float64),
  'currentWeightKg' : IDL.Float64,
  'progressPercent' : IDL.Float64,
  'targetWeightKg' : IDL.Opt(IDL.Float64),
});
export const WeightEntry = IDL.Record({
  'userId' : UserId,
  'entryId' : IDL.Nat,
  'weightKg' : IDL.Float64,
  'loggedAt' : Timestamp,
});
export const UserStats = IDL.Record({
  'averageDifficultyScore' : IDL.Float64,
  'totalWorkoutsCompleted' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const UserProfileInput = IDL.Record({
  'age' : IDL.Nat,
  'experienceLevel' : ExperienceLevel,
  'fitnessGoal' : FitnessGoal,
  'heightCm' : IDL.Float64,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'targetWeightKg' : IDL.Opt(IDL.Float64),
  'gender' : Gender,
});

export const idlService = IDL.Service({
  'generateWorkoutPlan' : IDL.Func([], [WeeklyWorkoutPlan], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCompletedWorkouts' : IDL.Func([], [IDL.Vec(CompletedWorkout)], ['query']),
  'getGoalPrediction' : IDL.Func([], [GoalPrediction], ['query']),
  'getLatestWorkoutPlan' : IDL.Func(
      [],
      [IDL.Opt(WeeklyWorkoutPlan)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkoutStats' : IDL.Func([], [UserStats], ['query']),
  'logWeight' : IDL.Func([IDL.Float64], [WeightEntry], []),
  'saveCallerUserProfile' : IDL.Func(
      [UserProfileInput],
      [UserProfilePublic],
      [],
    ),
  'submitWorkoutFeedback' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(Exercise), DifficultyFeedback],
      [CompletedWorkout],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Exercise = IDL.Record({
    'intensityDescriptor' : IDL.Text,
    'restSeconds' : IDL.Nat,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'muscleGroup' : IDL.Text,
  });
  const DayPlan = IDL.Record({
    'dayOfWeek' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'isRestDay' : IDL.Bool,
  });
  const Timestamp = IDL.Int;
  const WeeklyWorkoutPlan = IDL.Record({
    'planId' : IDL.Nat,
    'userId' : UserId,
    'days' : IDL.Vec(DayPlan),
    'generatedAt' : Timestamp,
    'intensityModifierAtGeneration' : IDL.Int,
    'weekNumber' : IDL.Nat,
  });
  const ExperienceLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const FitnessGoal = IDL.Variant({
    'weightLoss' : IDL.Null,
    'flexibility' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintenance' : IDL.Null,
    'endurance' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'age' : IDL.Nat,
    'experienceLevel' : ExperienceLevel,
    'fitnessGoal' : FitnessGoal,
    'heightCm' : IDL.Float64,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'weightKg' : IDL.Float64,
    'targetWeightKg' : IDL.Opt(IDL.Float64),
    'gender' : Gender,
    'intensityModifier' : IDL.Int,
  });
  const DifficultyFeedback = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CompletedWorkout = IDL.Record({
    'completedAt' : Timestamp,
    'completedId' : IDL.Nat,
    'planId' : IDL.Nat,
    'userId' : UserId,
    'dayOfWeek' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'difficultyFeedback' : DifficultyFeedback,
  });
  const GoalPrediction = IDL.Record({
    'weeklyRateKg' : IDL.Float64,
    'estimatedWeeksRemaining' : IDL.Opt(IDL.Float64),
    'currentWeightKg' : IDL.Float64,
    'progressPercent' : IDL.Float64,
    'targetWeightKg' : IDL.Opt(IDL.Float64),
  });
  const WeightEntry = IDL.Record({
    'userId' : UserId,
    'entryId' : IDL.Nat,
    'weightKg' : IDL.Float64,
    'loggedAt' : Timestamp,
  });
  const UserStats = IDL.Record({
    'averageDifficultyScore' : IDL.Float64,
    'totalWorkoutsCompleted' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const UserProfileInput = IDL.Record({
    'age' : IDL.Nat,
    'experienceLevel' : ExperienceLevel,
    'fitnessGoal' : FitnessGoal,
    'heightCm' : IDL.Float64,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'targetWeightKg' : IDL.Opt(IDL.Float64),
    'gender' : Gender,
  });
  
  return IDL.Service({
    'generateWorkoutPlan' : IDL.Func([], [WeeklyWorkoutPlan], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCompletedWorkouts' : IDL.Func(
        [],
        [IDL.Vec(CompletedWorkout)],
        ['query'],
      ),
    'getGoalPrediction' : IDL.Func([], [GoalPrediction], ['query']),
    'getLatestWorkoutPlan' : IDL.Func(
        [],
        [IDL.Opt(WeeklyWorkoutPlan)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getWorkoutStats' : IDL.Func([], [UserStats], ['query']),
    'logWeight' : IDL.Func([IDL.Float64], [WeightEntry], []),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfileInput],
        [UserProfilePublic],
        [],
      ),
    'submitWorkoutFeedback' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(Exercise), DifficultyFeedback],
        [CompletedWorkout],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };