/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    intensityDescriptor: string;
    restSeconds: bigint;
    name: string;
    reps: bigint;
    sets: bigint;
    muscleGroup: string;
}
export type Timestamp = bigint;
export interface GoalPrediction {
    weeklyRateKg: number;
    estimatedWeeksRemaining?: number;
    currentWeightKg: number;
    progressPercent: number;
    targetWeightKg?: number;
}
export interface UserProfilePublic {
    age: bigint;
    experienceLevel: ExperienceLevel;
    fitnessGoal: FitnessGoal;
    heightCm: number;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    weightKg: number;
    targetWeightKg?: number;
    gender: Gender;
    intensityModifier: bigint;
}
export interface DayPlan {
    dayOfWeek: string;
    exercises: Array<Exercise>;
    isRestDay: boolean;
}
export type UserId = Principal;
export interface CompletedWorkout {
    completedAt: Timestamp;
    completedId: bigint;
    planId: bigint;
    userId: UserId;
    dayOfWeek: string;
    exercises: Array<Exercise>;
    difficultyFeedback: DifficultyFeedback;
}
export interface WeeklyWorkoutPlan {
    planId: bigint;
    userId: UserId;
    days: Array<DayPlan>;
    generatedAt: Timestamp;
    intensityModifierAtGeneration: bigint;
    weekNumber: bigint;
}
export interface UserProfileInput {
    age: bigint;
    experienceLevel: ExperienceLevel;
    fitnessGoal: FitnessGoal;
    heightCm: number;
    name: string;
    weightKg: number;
    targetWeightKg?: number;
    gender: Gender;
}
export interface WeightEntry {
    userId: UserId;
    entryId: bigint;
    weightKg: number;
    loggedAt: Timestamp;
}
export interface UserStats {
    averageDifficultyScore: number;
    totalWorkoutsCompleted: bigint;
    currentStreak: bigint;
}
export enum DifficultyFeedback {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum ExperienceLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum FitnessGoal {
    weightLoss = "weightLoss",
    flexibility = "flexibility",
    muscleGain = "muscleGain",
    maintenance = "maintenance",
    endurance = "endurance"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export interface backendInterface {
    generateWorkoutPlan(): Promise<WeeklyWorkoutPlan>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCompletedWorkouts(): Promise<Array<CompletedWorkout>>;
    getGoalPrediction(): Promise<GoalPrediction>;
    getLatestWorkoutPlan(): Promise<WeeklyWorkoutPlan | null>;
    getUserProfile(user: Principal): Promise<UserProfilePublic | null>;
    getWeightHistory(): Promise<Array<WeightEntry>>;
    getWorkoutStats(): Promise<UserStats>;
    logWeight(weightKg: number): Promise<WeightEntry>;
    saveCallerUserProfile(input: UserProfileInput): Promise<UserProfilePublic>;
    submitWorkoutFeedback(planId: bigint, dayOfWeek: string, exercises: Array<Exercise>, feedback: DifficultyFeedback): Promise<CompletedWorkout>;
}
import type { CompletedWorkout as _CompletedWorkout, DifficultyFeedback as _DifficultyFeedback, Exercise as _Exercise, ExperienceLevel as _ExperienceLevel, FitnessGoal as _FitnessGoal, Gender as _Gender, GoalPrediction as _GoalPrediction, Timestamp as _Timestamp, UserId as _UserId, UserProfileInput as _UserProfileInput, UserProfilePublic as _UserProfilePublic, WeeklyWorkoutPlan as _WeeklyWorkoutPlan } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async generateWorkoutPlan(): Promise<WeeklyWorkoutPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.generateWorkoutPlan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateWorkoutPlan();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedWorkouts(): Promise<Array<CompletedWorkout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedWorkouts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedWorkouts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoalPrediction(): Promise<GoalPrediction> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoalPrediction();
                return from_candid_GoalPrediction_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoalPrediction();
            return from_candid_GoalPrediction_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestWorkoutPlan(): Promise<WeeklyWorkoutPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestWorkoutPlan();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestWorkoutPlan();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightHistory(): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightHistory();
            return result;
        }
    }
    async getWorkoutStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutStats();
            return result;
        }
    }
    async logWeight(arg0: number): Promise<WeightEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.logWeight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWeight(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitWorkoutFeedback(arg0: bigint, arg1: string, arg2: Array<Exercise>, arg3: DifficultyFeedback): Promise<CompletedWorkout> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWorkoutFeedback(arg0, arg1, arg2, to_candid_DifficultyFeedback_n27(this._uploadFile, this._downloadFile, arg3));
                return from_candid_CompletedWorkout_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWorkoutFeedback(arg0, arg1, arg2, to_candid_DifficultyFeedback_n27(this._uploadFile, this._downloadFile, arg3));
            return from_candid_CompletedWorkout_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CompletedWorkout_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompletedWorkout): CompletedWorkout {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyFeedback_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyFeedback): DifficultyFeedback {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceLevel_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessGoal_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessGoal): FitnessGoal {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_GoalPrediction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalPrediction): GoalPrediction {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeeklyWorkoutPlan]): WeeklyWorkoutPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Timestamp;
    completedId: bigint;
    planId: bigint;
    userId: _UserId;
    dayOfWeek: string;
    exercises: Array<_Exercise>;
    difficultyFeedback: _DifficultyFeedback;
}): {
    completedAt: Timestamp;
    completedId: bigint;
    planId: bigint;
    userId: UserId;
    dayOfWeek: string;
    exercises: Array<Exercise>;
    difficultyFeedback: DifficultyFeedback;
} {
    return {
        completedAt: value.completedAt,
        completedId: value.completedId,
        planId: value.planId,
        userId: value.userId,
        dayOfWeek: value.dayOfWeek,
        exercises: value.exercises,
        difficultyFeedback: from_candid_DifficultyFeedback_n14(_uploadFile, _downloadFile, value.difficultyFeedback)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyRateKg: number;
    estimatedWeeksRemaining: [] | [number];
    currentWeightKg: number;
    progressPercent: number;
    targetWeightKg: [] | [number];
}): {
    weeklyRateKg: number;
    estimatedWeeksRemaining?: number;
    currentWeightKg: number;
    progressPercent: number;
    targetWeightKg?: number;
} {
    return {
        weeklyRateKg: value.weeklyRateKg,
        estimatedWeeksRemaining: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.estimatedWeeksRemaining)),
        currentWeightKg: value.currentWeightKg,
        progressPercent: value.progressPercent,
        targetWeightKg: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.targetWeightKg))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    experienceLevel: _ExperienceLevel;
    fitnessGoal: _FitnessGoal;
    heightCm: number;
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    weightKg: number;
    targetWeightKg: [] | [number];
    gender: _Gender;
    intensityModifier: bigint;
}): {
    age: bigint;
    experienceLevel: ExperienceLevel;
    fitnessGoal: FitnessGoal;
    heightCm: number;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    weightKg: number;
    targetWeightKg?: number;
    gender: Gender;
    intensityModifier: bigint;
} {
    return {
        age: value.age,
        experienceLevel: from_candid_ExperienceLevel_n4(_uploadFile, _downloadFile, value.experienceLevel),
        fitnessGoal: from_candid_FitnessGoal_n6(_uploadFile, _downloadFile, value.fitnessGoal),
        heightCm: value.heightCm,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        weightKg: value.weightKg,
        targetWeightKg: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.targetWeightKg)),
        gender: from_candid_Gender_n9(_uploadFile, _downloadFile, value.gender),
        intensityModifier: value.intensityModifier
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): DifficultyFeedback {
    return "easy" in value ? DifficultyFeedback.easy : "hard" in value ? DifficultyFeedback.hard : "medium" in value ? DifficultyFeedback.medium : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): ExperienceLevel {
    return "intermediate" in value ? ExperienceLevel.intermediate : "beginner" in value ? ExperienceLevel.beginner : "advanced" in value ? ExperienceLevel.advanced : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weightLoss: null;
} | {
    flexibility: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} | {
    endurance: null;
}): FitnessGoal {
    return "weightLoss" in value ? FitnessGoal.weightLoss : "flexibility" in value ? FitnessGoal.flexibility : "muscleGain" in value ? FitnessGoal.muscleGain : "maintenance" in value ? FitnessGoal.maintenance : "endurance" in value ? FitnessGoal.endurance : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompletedWorkout>): Array<CompletedWorkout> {
    return value.map((x)=>from_candid_CompletedWorkout_n12(_uploadFile, _downloadFile, x));
}
function to_candid_DifficultyFeedback_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyFeedback): _DifficultyFeedback {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceLevel_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_FitnessGoal_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): _FitnessGoal {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    experienceLevel: ExperienceLevel;
    fitnessGoal: FitnessGoal;
    heightCm: number;
    name: string;
    weightKg: number;
    targetWeightKg?: number;
    gender: Gender;
}): {
    age: bigint;
    experienceLevel: _ExperienceLevel;
    fitnessGoal: _FitnessGoal;
    heightCm: number;
    name: string;
    weightKg: number;
    targetWeightKg: [] | [number];
    gender: _Gender;
} {
    return {
        age: value.age,
        experienceLevel: to_candid_ExperienceLevel_n21(_uploadFile, _downloadFile, value.experienceLevel),
        fitnessGoal: to_candid_FitnessGoal_n23(_uploadFile, _downloadFile, value.fitnessGoal),
        heightCm: value.heightCm,
        name: value.name,
        weightKg: value.weightKg,
        targetWeightKg: value.targetWeightKg ? candid_some(value.targetWeightKg) : candid_none(),
        gender: to_candid_Gender_n25(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == ExperienceLevel.intermediate ? {
        intermediate: null
    } : value == ExperienceLevel.beginner ? {
        beginner: null
    } : value == ExperienceLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): {
    weightLoss: null;
} | {
    flexibility: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} | {
    endurance: null;
} {
    return value == FitnessGoal.weightLoss ? {
        weightLoss: null
    } : value == FitnessGoal.flexibility ? {
        flexibility: null
    } : value == FitnessGoal.muscleGain ? {
        muscleGain: null
    } : value == FitnessGoal.maintenance ? {
        maintenance: null
    } : value == FitnessGoal.endurance ? {
        endurance: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyFeedback): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == DifficultyFeedback.easy ? {
        easy: null
    } : value == DifficultyFeedback.hard ? {
        hard: null
    } : value == DifficultyFeedback.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
